# Lab 1.01 - Australian Athletes (ais)

In the Python cell below this one, paste all the imports you need for data analysis from the code examples (Numpy, Pandas, etc.).

In [4]:
import numpy as np
import scipy.stats as stats
import pandas as pd
from pandas.api.types import CategoricalDtype
import matplotlib.pyplot as plt
from statsmodels.graphics.mosaicplot import mosaic
import seaborn as sns

Declare a variable `ais` and use it to import the dataset from the CSV-file `ais.csv` in [the directory `data/`](https://github.com/HoGentTIN/dsai-en-labs/tree/main/data) of the [Github repository](https://github.com/HoGentTIN/dsai-en-labs/) for the lab assignments. You can import a dataset with a URL pointing to the raw contents of the CSV-file in the Github repository (see the code example!).

This dataset contains 202 observations of Australian athletes with a variety of blood values. You can find the codebook (i.e., the explanation of what each variable/column in the dataset means) in [data/ais.md](https://github.com/HoGentTIN/dsai-en-labs/blob/main/data/ais.md). Show the first few observations of this sample.

In [7]:
ais = pd.read_csv('https://raw.githubusercontent.com/HoGentTIN/dsai-labs/refs/heads/main/data/ais.csv')
ais.head()

,id,rcc,wcc,hc,hg,ferr,bmi,ssf,pcBfat,lbm,ht,wt,sex,sport
0,1,3.96,7.5,37.5,12.3,60,20.56,109.1,19.75,63.32,195.9,78.9,f,B_Ball
1,2,4.41,8.3,38.2,12.7,68,20.67,102.8,21.30,58.55,189.7,74.4,f,B_Ball
2,3,4.14,5.0,36.4,11.6,21,21.86,104.6,19.88,55.36,177.8,69.1,f,B_Ball
3,4,4.11,5.3,37.3,12.6,69,21.88,126.4,23.66,57.18,185.0,74.9,f,B_Ball
4,5,4.45,6.8,41.5,14.0,29,18.96,80.3,17.64,53.20,184.6,64.6,f,B_Ball

Get general information about this dataset:

- How many rows and columns does the dataset have?
- Show general information about each variable, specifically the number of empty fields and the type of each variable (e.g., int64, float64, object)
- How many columns of each type are there?
- What is the measurement level (nominal, ordinal, interval, ratio) of each variable?

In [10]:
print(f"Number of columns: {len(ais.columns)}")
print("*"*50)
ais.info()
print("*"*50)
print(ais.dtypes.value_counts())

# rcc = Ratio
# wcc = Ratio
# hc = Ratio
# hg = Ratio
# ferr = Ratio
# bmi = Ratio
# ssf = Ratio
# pcBfat = Ratio
# lbm = Ratio
# ht = Ratio
# wt = Ratio
# sex = Nominaal
# sport = Nominaal

Number of columns: 14
**************************************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      202 non-null    int64
 1   rcc     202 non-null    float64
 2   wcc     202 non-null    float64
 3   hc      202 non-null    float64
 4   hg      202 non-null    float64
 5   ferr    202 non-null    int64
 6   bmi     202 non-null    float64
 7   ssf     202 non-null    float64
 8   pcBfat  202 non-null    float64
 9   lbm     202 non-null    float64
 10  ht      202 non-null    float64
 11  wt      202 non-null    float64
 12  sex     202 non-null    object
 13  sport   202 non-null    object
dtypes: float64(10), int64(2), object(2)
memory usage: 22.2+ KB
**************************************************
float64    10
int64       2
object      2
Name: count, dtype: int64

The column "id" is not an actual variable, but an index. Mark it as such.

In [11]:
ais.set_index(['id'])

,rcc,wcc,hc,hg,ferr,bmi,ssf,pcBfat,lbm,ht,wt,sex,sport
id,,,,,,,,,,,,,
1,3.96,7.5,37.5,12.3,60,20.56,109.1,19.75,63.32,195.9,78.9,f,B_Ball
2,4.41,8.3,38.2,12.7,68,20.67,102.8,21.30,58.55,189.7,74.4,f,B_Ball
3,4.14,5.0,36.4,11.6,21,21.86,104.6,19.88,55.36,177.8,69.1,f,B_Ball
4,4.11,5.3,37.3,12.6,69,21.88,126.4,23.66,57.18,185.0,74.9,f,B_Ball
5,4.45,6.8,41.5,14.0,29,18.96,80.3,17.64,53.20,184.6,64.6,f,B_Ball
...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,4.90,7.6,45.6,16.0,90,27.56,67.2,11.79,82.00,183.9,93.2,m,W_Polo
199,5.66,8.3,50.2,17.7,38,23.76,56.5,10.05,72.00,183.5,80.0,m,Tennis
200,5.03,6.4,42.7,14.3,122,22.01,47.6,8.51,68.00,183.1,73.8,m,Tennis
201,4.97,8.8,43.0,14.9,233,22.34,60.4,11.50,63.00,178.4,71.1,m,Tennis
202,5.38,6.3,46.0,15.7,32,21.07,34.9,6.26,72.00,190.8,76.7,m,Tennis

The variables that are now considered "object" are qualitative variables. Change the type of each of these variables to "category". For ordinal variables, also define a type and impose an order. Verify that the conversion was successful by requesting info about the types again.

In [ ]:
ais.sex = ais.sex.astype('category')
ais.sport = ais.sport.astype('category')

# ToDo: voor ordinaal

Describe the columns `ferr`, `bmi`, `sex` and `sport` and the unique values in each of these columns. Do you recognize the characteristics of qualitative and quantitative variables in the result?

In [34]:
ais[['ferr', 'bmi', 'sex', 'sport']].describe(include='all')

              ferr         bmi  sex sport
count   202.000000  202.000000  202   202
unique         NaN         NaN    2    10
top            NaN         NaN    m   Row
freq           NaN         NaN  102    37
mean     76.876238   22.955891  NaN   NaN
std      47.501239    2.863933  NaN   NaN
min       8.000000   16.750000  NaN   NaN
25%      41.250000   21.082500  NaN   NaN
50%      65.500000   22.720000  NaN   NaN
75%      97.000000   24.465000  NaN   NaN
max     234.000000   34.420000  NaN   NaN

Select following elements from the dataset:

- the second row (ids = 2)
- rows 4 to 6 (ids = 5 to 7)
- Columns 6 to 8 (`ferr`, `bmi`, `ssf`)
- the variable `pcBfat` (by name!). There are multiple ways to retrieve this!
- all observations for the sport "Netball"
- just the variable `wt` of the observations for "Netball"
- which sports are played by athletes with a BMI higher than 26? Also, provide a list of the unique values and a frequency table of how often each sport occurs.

In [30]:
# the second row (ids = 2)
print(ais.iloc[2])
print("*"*50)
# rows 4 to 6 (ids = 5 to 7)
print(ais.iloc[5:7])
print("*"*50)
# Columns 6 to 8 (ferr, bmi, ssf)
print(ais.iloc[:, 5:8])
print("*"*50)
# the variable pcBfat (by name!)
print(ais['pcBfat'])
print("*"*50)
# all observations for the sport "Netball"
print(ais[ais.sport == 'Netball'])
print("*"*50)
# just the variable wt of the observations for "Netball"
print(ais[ais.sport == 'Netball']['wt'])
print("*"*50)
# which sports are played by athletes with a BMI higher than 26?
print(ais[ais.bmi > 26])
print("*"*50)
# Also, provide a list of the unique values and a frequency table of how often each sport occurs
print(ais['sport'].unique())
print("*"*50)
print(ais['sport'].value_counts())

id             3
rcc         4.14
wcc          5.0
hc          36.4
hg          11.6
ferr          21
bmi        21.86
ssf        104.6
pcBfat     19.88
lbm        55.36
ht         177.8
wt          69.1
sex            f
sport     B_Ball
Name: 2, dtype: object
**************************************************
   id   rcc  wcc    hc    hg  ferr    bmi   ssf  pcBfat    lbm     ht    wt  \
5   6  4.10  4.4  37.4  12.5    42  21.04  75.2   15.58  53.77  174.0  63.7
6   7  4.31  5.3  39.6  12.8    73  21.69  87.2   19.99  60.17  186.2  75.2

  sex   sport
5   f  B_Ball
6   f  B_Ball
**************************************************
     ferr    bmi    ssf
0      60  20.56  109.1
1      68  20.67  102.8
2      21  21.86  104.6
3      69  21.88  126.4
4      29  18.96   80.3
..    ...    ...    ...
197    90  27.56   67.2
198    38  23.76   56.5
199   122  22.01   47.6
200   233  22.34   60.4
201    32  21.07   34.9

[202 rows x 3 columns]
**************************************************
0      19.75
1      21.30
2      19.88
3      23.66
4      17.64
       ...
197    11.79
198    10.05
199     8.51
200    11.50
201     6.26
Name: pcBfat, Length: 202, dtype: float64
**************************************************
    id   rcc   wcc    hc    hg  ferr    bmi    ssf  pcBfat    lbm     ht  \
35  36  4.56  13.3  42.2  13.6    20  19.16   49.0   11.29  53.14  176.8
36  37  4.15   6.0  38.0  12.7    59  21.15  110.2   25.26  47.09  172.6
37  38  4.16   7.6  37.5  12.3    22  21.40   89.0   19.39  53.44  176.0
38  39  4.32   6.4  37.7  12.3    30  21.03   98.3   19.63  48.78  169.9
39  40  4.06   5.8  38.7  12.8    78  21.77  122.1   23.11  56.05  183.0
40  41  4.12   6.1  36.6  11.8    21  21.38   90.4   16.86  56.45  178.2
41  42  4.17   5.0  37.4  12.7   109  21.47  106.9   21.32  53.11  177.3
42  43  3.80   6.6  36.5  12.4   102  24.45  156.6   26.57  54.41  174.1
43  44  3.96   5.5  36.3  12.4    71  22.63  101.1   17.93  55.97  173.6
44  45  4.44   9.7  41.4  14.1    64  22.80  126.4   24.97  51.62  173.7
45  46  4.27  10.6  37.7  12.5    68  23.58  114.0   22.62  58.27  178.7
46  47  3.90   6.3  35.9  12.1    78  20.06   70.0   15.01  57.28  183.3
47  48  4.02   9.1  37.7  12.7   107  23.01   77.0   18.14  57.30  174.4
48  49  4.39   9.6  38.3  12.5    39  24.64  148.9   26.78  54.18  173.3
49  50  4.52   5.1  38.8  13.1    58  18.26   80.1   17.22  42.96  168.6
50  51  4.25  10.7  39.5  13.2   127  24.47  156.6   26.50  54.46  174.0
51  52  4.46  10.9  39.7  13.7   102  23.99  115.9   23.01  57.20  176.0
52  53  4.40   9.3  40.4  13.6    86  26.24  181.7   30.10  54.38  172.2
53  54  4.83   8.4  41.8  13.4    40  20.04   71.6   13.93  57.58  182.7
54  55  4.23   6.9  38.3  12.6    50  25.72  143.5   26.65  61.46  180.5
55  56  4.24   8.4  37.6  12.5    58  25.64  200.8   35.52  53.46  179.8
56  57  3.95   6.6  38.4  12.8    33  19.87   68.9   15.59  54.11  179.6
57  58  4.03   8.5  37.7  13.0    51  23.35  103.6   19.61  55.35  171.7

      wt sex    sport
35  59.9   f  Netball
36  63.0   f  Netball
37  66.3   f  Netball
38  60.7   f  Netball
39  72.9   f  Netball
40  67.9   f  Netball
41  67.5   f  Netball
42  74.1   f  Netball
43  68.2   f  Netball
44  68.8   f  Netball
45  75.3   f  Netball
46  67.4   f  Netball
47  70.0   f  Netball
48  74.0   f  Netball
49  51.9   f  Netball
50  74.1   f  Netball
51  74.3   f  Netball
52  77.8   f  Netball
53  66.9   f  Netball
54  83.8   f  Netball
55  82.9   f  Netball
56  64.1   f  Netball
57  68.8   f  Netball
**************************************************
35    59.9
36    63.0
37    66.3
38    60.7
39    72.9
40    67.9
41    67.5
42    74.1
43    68.2
44    68.8
45    75.3
46    67.4
47    70.0
48    74.0
49    51.9
50    74.1
51    74.3
52    77.8
53    66.9
54    83.8
55    82.9
56    64.1
57    68.8
Name: wt, dtype: float64
**************************************************
      id   rcc   wcc    hc    hg  ferr    bmi    ssf  pcBfat     lbm     ht  \
52    53  4.40   9.3  40.4  13.6    86  26.24  181.7   30.10   54.38  172.2
69    70  4.58   5.8  42.1  14.7   164  28.57  109.6   21.30   68.86  175.0
70    71  4.81   6.8  42.7  15.3    50  26.95   98.5   20.10   63.04  171.1
71    72  4.51   9.0  39.7  14.3    36  28.13  136.3   24.88   63.03  172.7
72    73  4.77   7.1  40.6  14.6    40  26.85  103.6   19.26   66.85  175.6
74    75  4.75   7.5  43.8  15.2    90  31.93  131.9   23.01   72.98  172.3
109  110  4.87   4.8  44.9  15.4   124  26.25   65.3   11.72   81.00  187.2
112  113  4.32   4.3  41.6  14.0   177  26.73   35.2    6.46   91.00  190.4
121  122  5.40   6.8  49.5  17.3   183  26.07   44.7    8.61   82.00  185.6
124  125  5.09  10.1  44.9  14.8   118  26.79   58.3    9.79   83.00  185.6
144  145  5.09   8.9  46.3  15.4    44  29.97   71.1   13.97   88.00  185.1
145  146  5.11   9.6  48.2  16.7   103  27.39   65.9   11.66   83.00  185.5
159  160  5.48   4.6  49.4  18.0   132  32.52   55.7    8.51  102.00  185.0
161  162  5.01   8.9  46.0  15.9   212  30.18  112.5   19.94   78.00  180.1
162  163  5.48   6.2  48.2  16.3    94  34.42   82.7   13.91  106.00  189.2
175  176  5.50   6.4  48.1  16.5    40  26.51   52.8    9.40   86.00  189.1
177  178  4.96   8.3  45.3  15.7   141  33.73  113.5   17.41   89.00  179.1
178  179  5.01   8.9  46.0  15.9   212  30.18   96.9   18.08   80.00  180.1
191  192  5.08   8.5  46.3  15.6   117  26.86   75.6   14.98   86.00  193.9
195  196  5.34   6.2  49.8  17.2   143  27.79   75.7   13.49   82.00  184.6
197  198  4.90   7.6  45.6  16.0    90  27.56   67.2   11.79   82.00  183.9

        wt sex    sport
52    77.8   f  Netball
69    87.5   f    Field
70    78.9   f    Field
71    83.9   f    Field
72    82.8   f    Field
74    94.8   f    Field
109   92.0   m     Swim
112   96.9   m     Swim
121   89.8   m      Row
124   92.3   m      Row
144  102.7   m    Field
145   94.2   m    Field
159  111.3   m    Field
161   97.9   m    Field
162  123.2   m    Field
175   94.8   m  T_Sprnt
177  108.2   m    Field
178   97.9   m    Field
191  101.0   m   W_Polo
195   94.7   m   W_Polo
197   93.2   m   W_Polo
**************************************************
Unieke sporten:
['B_Ball' 'Row' 'Netball' 'Swim' 'Field' 'T_400m' 'T_Sprnt' 'Tennis' 'Gym'
 'W_Polo']
**************************************************
sport
Row        37
T_400m     29
B_Ball     25
Netball    23
Swim       22
Field      19
W_Polo     17
T_Sprnt    15
Tennis     11
Gym         4
Name: count, dtype: int64